/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab.pkg5;

import java.util.HashSet;
import javax.swing.DefaultListModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author david
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_mundo = new javax.swing.JDialog();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_ntor = new javax.swing.JTextField();
        tf_pesot = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jd_criatura = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tf_nraza = new javax.swing.JTextField();
        tf_energia = new javax.swing.JTextField();
        tf_lifespan = new javax.swing.JTextField();
        tf_region = new javax.swing.JTextField();
        tf_vivos = new javax.swing.JTextField();
        tf_pesoc = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jd_universo = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tf_codigouni = new javax.swing.JTextField();
        tf_edaduni = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jm_criaturas = new javax.swing.JPopupMenu();
        jm_modificar = new javax.swing.JMenuItem();
        jm_eliminar = new javax.swing.JMenuItem();
        jd_modificarc = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        tf_mvivos = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tf_mregion = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jd_modificarm = new javax.swing.JDialog();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tf_mnombrem = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jm_mundo = new javax.swing.JPopupMenu();
        jm_mmodificar = new javax.swing.JMenuItem();
        jm_meliminar = new javax.swing.JMenuItem();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_mundos = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_criatura = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jt_universo = new javax.swing.JTree();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        jButton4.setText("Agregar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jLabel2.setText("nombre de la tortuga");

        jLabel3.setText("peso");

        jLabel4.setText("nuevo mundo");

        javax.swing.GroupLayout jd_mundoLayout = new javax.swing.GroupLayout(jd_mundo.getContentPane());
        jd_mundo.getContentPane().setLayout(jd_mundoLayout);
        jd_mundoLayout.setHorizontalGroup(
            jd_mundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_mundoLayout.createSequentialGroup()
                .addGroup(jd_mundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_mundoLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jd_mundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(61, 61, 61)
                        .addGroup(jd_mundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_ntor, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                            .addComponent(tf_pesot)))
                    .addGroup(jd_mundoLayout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jButton4))
                    .addGroup(jd_mundoLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jd_mundoLayout.setVerticalGroup(
            jd_mundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_mundoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_mundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_ntor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jd_mundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_pesot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jButton4)
                .addContainerGap())
        );

        jLabel5.setText("nombre de la raza");

        jLabel6.setText("energia");

        jLabel7.setText("largo de vida");

        jLabel8.setText("region");

        jLabel9.setText("numero de vivos");

        jLabel10.setText("peso");

        jLabel11.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel11.setText("nueva raza");

        jButton5.setText("agregar");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_criaturaLayout = new javax.swing.GroupLayout(jd_criatura.getContentPane());
        jd_criatura.getContentPane().setLayout(jd_criaturaLayout);
        jd_criaturaLayout.setHorizontalGroup(
            jd_criaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_criaturaLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jd_criaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jd_criaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_nraza)
                    .addComponent(tf_energia)
                    .addComponent(tf_lifespan)
                    .addComponent(tf_region)
                    .addComponent(tf_vivos)
                    .addComponent(tf_pesoc, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                .addGap(49, 49, 49))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_criaturaLayout.createSequentialGroup()
                .addContainerGap(179, Short.MAX_VALUE)
                .addGroup(jd_criaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_criaturaLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_criaturaLayout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addGap(207, 207, 207))))
        );
        jd_criaturaLayout.setVerticalGroup(
            jd_criaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_criaturaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_criaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_criaturaLayout.createSequentialGroup()
                        .addGroup(jd_criaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(tf_nraza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jd_criaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tf_energia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jd_criaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tf_lifespan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jd_criaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tf_region, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addComponent(jLabel9))
                    .addComponent(tf_vivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jd_criaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_pesoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel12.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel12.setText("nuevo universo");

        jLabel13.setText("codigo de universo");

        jLabel14.setText("edad de universo");

        jButton8.setText("agregar");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_universoLayout = new javax.swing.GroupLayout(jd_universo.getContentPane());
        jd_universo.getContentPane().setLayout(jd_universoLayout);
        jd_universoLayout.setHorizontalGroup(
            jd_universoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_universoLayout.createSequentialGroup()
                .addGroup(jd_universoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_universoLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel12))
                    .addGroup(jd_universoLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jd_universoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addGroup(jd_universoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_codigouni)
                            .addComponent(tf_edaduni, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)))
                    .addGroup(jd_universoLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jButton8)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jd_universoLayout.setVerticalGroup(
            jd_universoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_universoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(jd_universoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tf_codigouni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jd_universoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tf_edaduni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addContainerGap())
        );

        jm_modificar.setText("modificar");
        jm_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_modificarActionPerformed(evt);
            }
        });
        jm_criaturas.add(jm_modificar);

        jm_eliminar.setText("eliminar");
        jm_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_eliminarActionPerformed(evt);
            }
        });
        jm_criaturas.add(jm_eliminar);

        jLabel15.setText("cantidad de vivos");

        jLabel16.setText("region");

        jLabel17.setText("modificar");

        jButton9.setText("agregar");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_modificarcLayout = new javax.swing.GroupLayout(jd_modificarc.getContentPane());
        jd_modificarc.getContentPane().setLayout(jd_modificarcLayout);
        jd_modificarcLayout.setHorizontalGroup(
            jd_modificarcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modificarcLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jd_modificarcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_modificarcLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addGroup(jd_modificarcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_mvivos)
                    .addComponent(tf_mregion, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                .addContainerGap(89, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_modificarcLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jd_modificarcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton9)
                    .addComponent(jLabel17))
                .addGap(165, 165, 165))
        );
        jd_modificarcLayout.setVerticalGroup(
            jd_modificarcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modificarcLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel17)
                .addGap(27, 27, 27)
                .addGroup(jd_modificarcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tf_mvivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_modificarcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_mregion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jd_modificarcLayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addContainerGap())
        );

        jLabel18.setText("modificar mundo");

        jLabel19.setText("nombre");

        jButton10.setText("modificar");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_modificarmLayout = new javax.swing.GroupLayout(jd_modificarm.getContentPane());
        jd_modificarm.getContentPane().setLayout(jd_modificarmLayout);
        jd_modificarmLayout.setHorizontalGroup(
            jd_modificarmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modificarmLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel19)
                .addGroup(jd_modificarmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_modificarmLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jd_modificarmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_modificarmLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jButton10))
                            .addComponent(jLabel18)))
                    .addGroup(jd_modificarmLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(tf_mnombrem, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        jd_modificarmLayout.setVerticalGroup(
            jd_modificarmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modificarmLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel18)
                .addGap(38, 38, 38)
                .addGroup(jd_modificarmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(tf_mnombrem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jm_mmodificar.setText("modificar");
        jm_mmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_mmodificarActionPerformed(evt);
            }
        });
        jm_mundo.add(jm_mmodificar);

        jm_meliminar.setText("eliminar");
        jm_meliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_meliminarActionPerformed(evt);
            }
        });
        jm_mundo.add(jm_meliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Agregar mundo disco");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Agregar criatura");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel1.setText("Menu principal");

        jl_mundos.setModel(new DefaultListModel());
        jl_mundos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_mundosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jl_mundos);

        jl_criatura.setModel(new DefaultListModel());
        jl_criatura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_criaturaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jl_criatura);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Universo");
        jt_universo.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane3.setViewportView(jt_universo);

        jButton3.setText("Agregar al arbol");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton6.setText("agregar al arbol");

        jButton7.setText("Agregar universo");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addGap(33, 33, 33)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))))
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        jd_mundo.setModal(true);
        jd_mundo.pack();
        jd_mundo.setLocationRelativeTo(this);
        jd_mundo.setVisible(true);

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        DefaultListModel modelo = (DefaultListModel) jl_mundos.getModel();
        String nombre = tf_ntor.getText();
        int peso = Integer.parseInt(tf_pesot.getText());
        modelo.addElement(new mundo(nombre, peso));
        tf_ntor.setText("");
        tf_pesot.setText("");
        jd_mundo.dispose();
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        jd_criatura.setModal(true);
        jd_criatura.pack();
        jd_criatura.setLocationRelativeTo(this);
        jd_criatura.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        DefaultListModel modelo = (DefaultListModel) jl_criatura.getModel();
        String nombre = tf_nraza.getText();
        int energia = Integer.parseInt(tf_energia.getText());
        int lifespan = Integer.parseInt(tf_lifespan.getText());
        String region = tf_region.getText();
        int vivos = Integer.parseInt(tf_vivos.getText());
        int peso = Integer.parseInt(tf_pesoc.getText());
        modelo.addElement(new criaturas(nombre, energia, lifespan, region, vivos, peso));
        tf_nraza.setText("");
        tf_energia.setText("");
        tf_lifespan.setText("");
        tf_region.setText("");
        tf_vivos.setText("");
        tf_pesoc.setText("");
        jd_criatura.dispose();
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        if (jButton7.isEnabled()) {
            jd_universo.setModal(true);
            jd_universo.pack();
            jd_universo.setLocationRelativeTo(this);
            jd_universo.setVisible(true);
        }
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:
        String codigo = tf_codigouni.getText();
        int edad = Integer.parseInt(tf_edaduni.getText());
        DefaultTreeModel m = (DefaultTreeModel) jt_universo.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
        DefaultMutableTreeNode nodo_universo = (new DefaultMutableTreeNode(new Universo(codigo, edad)));
        raiz.add(nodo_universo);
        m.reload();
        jd_universo.dispose();
        jButton7.setEnabled(false);
    }//GEN-LAST:event_jButton8MouseClicked

    private void jl_mundosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_mundosMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            jm_mundo.show(evt.getComponent(),evt.getX() , evt.getY());
        }
    }//GEN-LAST:event_jl_mundosMouseClicked

    private void jl_criaturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_criaturaMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            if (jl_criatura.getSelectedIndex() >= 0) {
                jm_criaturas.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_jl_criaturaMouseClicked

    private void jm_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_eliminarActionPerformed
        // TODO add your handling code here:
        DefaultListModel modelo = (DefaultListModel) jl_criatura.getModel();
        modelo.remove(jl_criatura.getSelectedIndex());
    }//GEN-LAST:event_jm_eliminarActionPerformed

    private void jm_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_modificarActionPerformed
        // TODO add your handling code here:
        jd_modificarc.setModal(true);
        jd_modificarc.pack();
        jd_modificarc.setLocationRelativeTo(this);
        jd_modificarc.setVisible(true);
    }//GEN-LAST:event_jm_modificarActionPerformed

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        // TODO add your handling code here:
        DefaultListModel modelo = (DefaultListModel) jl_criatura.getModel();
        String nombre = ((criaturas)modelo.get(jl_criatura.getSelectedIndex())).getNombre();
        int energia = ((criaturas)modelo.get(jl_criatura.getSelectedIndex())).getEnergia();
        int lifespan = ((criaturas)modelo.get(jl_criatura.getSelectedIndex())).getMlife();
        String region = tf_mregion.getText();
        int vivos = Integer.parseInt(tf_mvivos.getText());
        int peso = ((criaturas)modelo.get(jl_criatura.getSelectedIndex())).getPeso();
        criaturas modi=new criaturas(nombre, energia, lifespan, region, vivos, peso);
        modelo.setElementAt(modi, jl_criatura.getSelectedIndex());
        jd_modificarc.dispose();
    }//GEN-LAST:event_jButton9MouseClicked

    private void jm_mmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_mmodificarActionPerformed
        // TODO add your handling code here:
        jd_modificarm.setModal(true);
        jd_modificarm.pack();
        jd_modificarm.setLocationRelativeTo(this);
        jd_modificarm.setVisible(true);
        
    }//GEN-LAST:event_jm_mmodificarActionPerformed

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        // TODO add your handling code here:
        DefaultListModel modelo = (DefaultListModel) jl_mundos.getModel();
        String nombre =tf_mnombrem.getText();
        int peso = ((mundo)modelo.get(jl_mundos.getSelectedIndex())).getPeso();
        mundo m=new mundo(nombre, peso);
        modelo.setElementAt(m, jl_mundos.getSelectedIndex());
        jd_modificarm.dispose();
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        if (jl_mundos.getSelectedIndex()>=0) {
            DefaultTreeModel m=(DefaultTreeModel)jt_universo.getModel();
            DefaultMutableTreeNode raiz=(DefaultMutableTreeNode) m.getRoot();
            DefaultListModel mlist=(DefaultListModel) jl_mundos.getModel();
            String nombre;
            int peso;
            nombre=((mundo)mlist.get(jl_mundos.getSelectedIndex())).getNombre();
            peso=((mundo)mlist.get(jl_mundos.getSelectedIndex())).getPeso();
            DefaultMutableTreeNode d=new DefaultMutableTreeNode(new mundo(nombre,peso));
            raiz.add(d);
            m.reload();
        }
        
    }//GEN-LAST:event_jButton3MouseClicked

    private void jm_meliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_meliminarActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        DefaultListModel modelo = (DefaultListModel) jl_mundos.getModel();
        modelo.remove(jl_mundos.getSelectedIndex());
    }//GEN-LAST:event_jm_meliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JDialog jd_criatura;
    private javax.swing.JDialog jd_modificarc;
    private javax.swing.JDialog jd_modificarm;
    private javax.swing.JDialog jd_mundo;
    private javax.swing.JDialog jd_universo;
    private javax.swing.JList<String> jl_criatura;
    private javax.swing.JList<String> jl_mundos;
    private javax.swing.JPopupMenu jm_criaturas;
    private javax.swing.JMenuItem jm_eliminar;
    private javax.swing.JMenuItem jm_meliminar;
    private javax.swing.JMenuItem jm_mmodificar;
    private javax.swing.JMenuItem jm_modificar;
    private javax.swing.JPopupMenu jm_mundo;
    private javax.swing.JTree jt_universo;
    private javax.swing.JTextField tf_codigouni;
    private javax.swing.JTextField tf_edaduni;
    private javax.swing.JTextField tf_energia;
    private javax.swing.JTextField tf_lifespan;
    private javax.swing.JTextField tf_mnombrem;
    private javax.swing.JTextField tf_mregion;
    private javax.swing.JTextField tf_mvivos;
    private javax.swing.JTextField tf_nraza;
    private javax.swing.JTextField tf_ntor;
    private javax.swing.JTextField tf_pesoc;
    private javax.swing.JTextField tf_pesot;
    private javax.swing.JTextField tf_region;
    private javax.swing.JTextField tf_vivos;
    // End of variables declaration//GEN-END:variables

}
